### ISSUE TITLE
Onboard new Github Org Owners

### ISSUE THREAD

**Issue by Lassulus** [nix-open-org/org-v2#14]
The NCA decided to form a new team to distribute the commit bit.
We decided that this team should be initialized with the following members:
@Mic92
@NickCao
@jtojnar

It would be good if those people can get the required permissions to fulfill that task :)

**Comment by zimbatm** [comment]
Ok!

Welcome to org ownership!

**Comment by jtojnar** [comment]
Thanks.

This gave me access to https://github.com/NixOS/nixpkgs/reported_content, are we supposed to do something about that or just focus on the commit bit stuff?

**Comment by Lassulus** [comment]
just focus on the commit bit stuff for now

**Comment by zimbatm** [comment]
I didn't want to block the NCA decision, but because of the least privileges, team maintainership is enough for the role.

Team maintainers can add other members from the org. Not external members. But here, I would expect people with commit bits to have been invited as a maintainer already.

**Comment by mweinelt** [comment]
Can the permissions be migrated as discussed, please?

**Comment by infinisil** [comment]
I pinged zimbatm to demote @NickCao (the others were demoted by @NickCao and apparently org owners can't demote themselves).

There's also now documentation on the process [here](https://github.com/NixOS/org/blob/main/doc/nixpkgs-committers.md), which the NCA will announce soon. Probably best to wait until the announcement before starting to make any changes.

**Comment by zimbatm** [comment]
Fixed. The three are not owners anymore, and are team maintainers.

Please close the issue if we're done with this.
