### ISSUE TITLE
Add renovate bot to NixOS infra

### ISSUE THREAD

**Issue by Mic92** [nix-open-org/org-v2#23]
I want to use renovate bot to update nixpkgs and keep the NixOS infra up-to-date.
I already requested the installation.

**Comment by Lassulus** [comment]
I accepted the installation request.

**Comment by infinisil** [comment]
In the future I'd like to establish a workflow of having something like an `actions` directory in the repo, where one can make PRs against to request actions to be taken, such as this one.
