### ISSUE TITLE
Nixpkgs committer delegation team cannot add people to the  Retired Nixpkgs Contributors team

### ISSUE THREAD

**Issue by Mic92** [nix-open-org/org-v2#25]
When inactive committers get removed, we usually add them to `Retired Nixpkgs Contributors`.
So we need also access to this team.

**Comment by Mic92** [comment]
Context: https://github.com/NixOS/nixpkgs/pull/337552

**Comment by Lassulus** [comment]
added @Mic92 @jtojnar and @NickCao to the retired nixpkgs contributors team as maintainers.
