### ISSUE TITLE
Update GitHub org owners to match reality

### ISSUE THREAD

**Issue by fricklerhandwerk** [nix-open-org/org-v2#29]
[GitHub org ownership](https://github.com/orgs/NixOS/people?query=role%3Aowner) currently seems to reflect a mishmash of historical state of affairs.

At the time of writing, the org owners are
- @domenkozar
- @garbas
- @zimbatm
- @edolstra
- @lassulus (added as [interim manager](https://discourse.nixos.org/t/constitutional-assembly-new-interim-github-org-owner/49636))

This is also documented in the [recently created org repo](https://github.com/NixOS/org/blob/main/doc/github.md#github), but without any plan of how to proceed.

There are no provisions in [the constitution](https://github.com/NixOS/nix-constitutional-assembly/blob/main/constitution.md) for how to deal with ownership, and what's there leaves open to interpretation if the steering committee should also have org owners status.

Whatever the outcome of the [2024 elections](https://github.com/NixOS/SC-election-2024/), I would ask for actual org owners to be responsible and available, not just exercise silent authority.

@Lassulus: Feel free to move this to https://github.com/NixOS/org if that's a better place to handle the issue.

**Comment by Lassulus** [comment]
The new SC should ultimately handle the org ownership. Of course it's also possible for them to delegate it to a dedicated team. So I would wait for the new SC to decide what they want to do with this responsibility and update the org owners afterwards? Or is there a reason to do this before the first SC is established?

**Comment by zimbatm** [comment]
@fricklerhandwerk was there any particular event that prompted you to write this message? AFAIK we are already operating as interim managers and not official "owners". This could be clarified here: https://github.com/NixOS/org/blob/main/doc/github.md#github

If you need something specific to get done, please reach out to https://matrix.to/#/#org_owners:nixos.org or by creating an issue on this repo.

**Comment by fricklerhandwerk** [comment]
@zimbatm nothing specific. But these things communicate something: who's responsible and in charge, and what to expect. If it's not aligned with what is actually the case, we'll be perpetuating the opaqueness and feeling of "something's weird" that's been plaguing the ecosystem for many years.

For example, for people not in the very inner circle it's not clear who will actually react to requests, how long it will take, and whether the resulting action will be generally accepted.

**Comment by zimbatm** [comment]
Fixed! See https://github.com/NixOS/org/blob/main/doc/github-org-owners.md
