### ISSUE TITLE
GitHub App for setting up better codeowner pings

### ISSUE THREAD

**Issue by infinisil** [nix-open-org/org-v2#31]
I need a GitHub App to implement https://github.com/NixOS/nixpkgs/pull/336261, because the standard GitHub Action tokens don't have sufficient permissions.

Instructions:
- Create new App ([direct link](https://github.com/organizations/NixOS/settings/apps/new))
  - Name: Nix Owners
  - Homepage URL: https://github.com/NixOS/nixpkgs
  - Disable Webhooks
  - Permissions:
    - Repository > Pull Requests: read-write (to request reviews)
    - Repository > Administration: read-only (indirectly needed to check whether a review can be requested)
    - Organization > Members: read-only (indirectly needed to check whether a review can be requested)
- Install the App on the NixOS, give it access to only https://github.com/nixos/nixpkgs
- Set the App ID as a new _repository variable_ ([direct link](https://github.com/NixOS/nixpkgs/settings/variables/actions/new)) named `OWNER_APP_ID`
- Generate a private key for the App and set it as a new _repository secret_ ([direct link](https://github.com/NixOS/nixpkgs/settings/secrets/actions/new)) named `OWNER_APP_PRIVATE_KEY`

**Comment by Lassulus** [comment]
ok, should be done
