### ISSUE TITLE
Repository for creating nixos-images

### ISSUE THREAD

**Issue by Mic92** [nix-open-org/org-v2#33]
@arianvp and me want to have a new repository for creating NixOS images.
Reason is that cache.nixos.org has a lot of images that no one will have download.
It saves costs, when we build these images outside of hydra.

**Comment by Mic92** [comment]
cc @Lassulus

**Comment by arianvp** [comment]
Proposed name would just be `images`

**Comment by arianvp** [comment]
I'd eventually plan to merge https://GitHub.com/NixOS/amis into this new repo

**Comment by zimbatm** [comment]
done: https://github.com/NixOS/images
