### ISSUE TITLE
Branch protection for nixos-hardware

### ISSUE THREAD

**Issue by Mic92** [nix-open-org/org-v2#42]
I just fat-fingered my remote push target (master instead of pull request).
Would be good if we could enforce all changes to go through pull requests.
Also no one should be able to delete master.

**Comment by infinisil** [comment]
Sounds good to me, so [if another org owner approves](https://github.com/NixOS/org/blob/main/doc/github-org-owners.md#authority-and-processes), this can be implemented.

**Comment by winterqt** [comment]
Done:
- restricted deletions
- requires all changes to be PR'd
- blocked force pushes
